### ISSUE TITLE
what's the meaning of 'natemode' in 'realintersection.cpp'?

### ISSUE THREAD

**Issue by Sparklexs** [lemire/SIMDIntersections#1]
Dear Lemire,
Thank your for opening your codes! After carefully reading your implementations of the related intersection algorithms, I have a question on the 'natemode' in 'realintersection.cpp' , which is hard to distinguish from the common mode of intersection, due to a lack of comments. From my point of view, 'natemode' seems to configuring only 'MaxBit' rather than set length 'S'.
    Also, there are some 'nate' intersection methods in 'mediumintersection.h', do they have some underlying relationships?
    The last question, implementation of paper 'Intersection in Integer Inverted Indices(2007)', namely 'skipping.h' seems to use buckets of fixed-length rather than most significant bit, aren't they?
    I have also augmented this repo with some algorithms of multiple sets intersection, which may help your job.
    thank you!

**Comment by lemire** [comment]
Thanks for your interest.

> (...) which is hard to distinguish from the common mode of intersection, due to a lack of comments. From my point of view, 'natemode' seems to configuring only 'MaxBit' rather than set length 'S'.

It is an undocumented hidden feature that I do not expect people to use. Basically, there are different ways to generate synthetic numbers, and I think you already understand the difference in this case... I have revised the code to explain that it is left undocumented on purpose...

https://github.com/lemire/SIMDIntersections/commit/0de9b0034b01aa35fedb54e6550abcbd654bb8bf

> Also, there are some 'nate' intersection methods in 'mediumintersection.h', do they have some underlying relationships?

Yes, they were all designed by my co-author @nkurz (who is called "nate"). It is not the best way to name things but this repository is a "research" repository so it is bound to be a tad messy. 

I have updated the comments to explain the origin of the names...

https://github.com/lemire/SIMDIntersections/commit/1bfbb3df1e09880965497085c1b14edf1cc074e5

> The last question, implementation of paper 'Intersection in Integer Inverted Indices(2007)', namely 'skipping.h' seems to use buckets of fixed-length rather than most significant bit, aren't they?

Sanders and Transier consider many alternatives. To make what is implemented clearer, I have added a comment in the code...

https://github.com/lemire/SIMDIntersections/commit/9bd47f7f5db6fee322dc834272315fff076d327a

> I have also augmented this repo with some algorithms of multiple sets intersection, which may help your job.

Would you be interested in issuing a pull-request from your fork after syncing with the latest code changes? In this way, we could discuss your changes and it might help spur and validate ideas, and collaboration? Just make sure that you label you work with your name so that you get credit.


I am going to close this, reopen if you have more questions.
